---

- hosts: all,!localhost
  become: yes
  tasks:
    - name: setup wtmp logrotate
      template:
        src: logrotate.conf.j2
        dest: /etc/logrotate.conf
        owner: root
        group: root
        mode: 0644
#        validate: "sudo -u root -g syslog /usr/sbin/logrotate -d -v %s"

    - name: setup auth.log logrotate
      template:
        src: logrotate.d.rsyslog.j2
        dest: /etc/logrotate.d/rsyslog
        owner: root
        group: root
        mode: 0644
#        validate: "sudo -u root -g syslog /usr/sbin/logrotate -d -v %s"
